### ISSUE TITLE
Map causes app to crash for some request from SOLR

### ISSUE THREAD

**Issue by nickdos** [ARGA-Genomes/arga-web#16]
Test site gives a blank white screen when map view is shown, when user tries to filter on `dataset` for refSeq.

Error message:

```
react_devtools_backend.js:4026 TypeError: Cannot read properties of null (reading 'length')
    at MapDataLayer.js:91:64
    at MapDataLayer.js:276:11
```

SOLR response for heatmap request:

```json
    "facet_heatmaps":{
      "quad":{
        "gridLevel":8,
        "columns":53,
        "rows":56,
        "minX":95.625,
        "maxX":170.15625,
        "minY":-46.40625,
        "maxY":-7.03125,
        "counts_ints2D":null}}}}
```

**Comment by nickdos** [comment]
QA on test site once deployed

**Comment by nickdos** [comment]
QA passed ✅
